---
    - name: Install mysql and related tools
      become: yes
      apt:
        state: present
        pkg:
         - mysql-server
         - python3-mysqldb
         - php-mysql

    - name: Copy .my.cnf file with root password credentials
      become: yes
      become_user: root
      template: src=roles/mysql/templates/.my.cnf dest=/root/.my.cnf owner=root group=root mode=0755

    - name: Set the root password
      become: yes
      mysql_user:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        check_implicit_admin: yes 
        name: root
        password: "{{ mysql_root_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Remove all anonymous user accounts
      mysql_user:
        name: ''
        host_all: yes
        state: absent
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Remove the MySQL test database
      mysql_db:
        name: test
        state: absent
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Creates database for WordPress
      mysql_db:
        name: wordpress
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Create MySQL user for WordPress
      mysql_user:
        name: worduser
        password: wordpass
        priv: wordpress.*:ALL
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"
