---
# tasks file for site-fail2ban
  - name: install apt fail2ban packages
    become: yes
    apt: 
      name: ['fail2ban', 'sendmail'] 
#      name: "{{ item }}"   
      state: latest
#    with_items:
#      - fail2ban
#      - sendmail

  - name: copy filter
    become: yes
    copy:
      src: /Users/olehhordon/Desktop/backup-lemp/roles/fail2ban/files/filter.d/
      dest: /etc/fail2ban/filter.d/
      owner: root
      group: root
      mode: 0644
#    with_items:
#       - ../files/*
#      - files/nginx-404.conf
#      - nginx-badbots.conf
#      - "../files/nginx-badrequests.conf"
#      - "../files/nginx-dos.conf"
#      - "../files/nginx-noscript.conf"
#      - "../files/wordpress.conf"

  - name: override the basic fail2ban configuration with .local file
    template: 
      src: ../templates/jail.local.j2 
      dest: /etc/fail2ban/jail.local 
      owner: root 
      group: root 
      mode: 0644
    notify:
        - restart fail2ban
    become: yes
